### ISSUE TITLE
Add warning/info for proposed Meanwell power supply in EU

### ISSUE THREAD

**Issue by Gitii** [blakadder/sv06#6]
Hi,

The proposed psu upgrade from Meanwell (LRS-350-24) is not officially available in EU.
It does not support EN61000-3-2.
It will (probably) not explode or burn your house down but may cause issues with other technical equipment in your house.

Excerpt from [the official manual](https://www.omc-stepperonline.com/download/LRS-350-24.pdf):
> 9. This power supply does not meet the harmonic current requirements outlined by BS EN/EN61000-3-2. Please do not use this power supply under the following conditions: 
a) the end-devices is used within the European Union, and 
b) the end-devices is connected to public mains supply With 220Vac or greater rated nominal voltage, and 
c) the power supply is:
\- installed in end-devices With average or continuous input power greater than 75W, or 
\- belong to part of a lighting system 

I think a warning or at least a note should be added to the page.
An alternative is RSP-320-24 (also from Meanwell) which has close-enough specs BUT (and this is very unfortunate) the fan is always on in this sku.

Thanks

**Comment by blakadder** [comment]
Weird because even Mouser carries it
https://eu.mouser.com/ProductDetail/MEAN-WELL/LRS-350-24?qs=ah3jBNVE1PT%252BkwLcackrGA%3D%3D

**Comment by Gitii** [comment]
Hi @blakadder,

for me, Mouser does display a warning:
![image](https://user-images.githubusercontent.com/4958574/233702723-56d8d507-5750-4cb8-b8c0-626c383d8e99.png)
Translation:
> Due to legal requirements, Mouser cannot sell this product in your country.

**Comment by blakadder** [comment]
must be a german thing, i'm also in the EU but don't get any warnings. I did put in a warning, doesn't hurt to have it there
